apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: address
spec:
  hosts:
    - address
  http:
    - fault:
        abort:
          percentage: 50
          httpStatus: 400
      route:
        - destination:
            host: address
            subset: v3